In [45]:
import pandas as pd
import numpy as np
from numpy.random import logistic
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import warnings; warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, StandardScaler, MinMaxScaler

In [46]:
cancer = pd.read_csv(r"C:\Users\dai\PycharmProjects\ML\Logistic_reg\BreastCancer.csv")
X = cancer.drop(["Code", "Class"], axis=1)
y = cancer["Class"]

In [47]:
def knn(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25, stratify=y)
    scores = []
    for n in range(1, 11):
        knn = KNeighborsClassifier(n_neighbors=n)
        knn.fit(X_train, y_train)
        y_pred = knn.predict(X_test)
        scores.append([accuracy_score(y_test, y_pred), n])

    scores = pd.DataFrame(scores, columns=["accuracy", "n"])
    scores.sort_values("accuracy", ascending=False)
    return scores
knn(X, y)

   accuracy   n
0  0.957143   1
1  0.933333   2
2  0.971429   3
3  0.961905   4
4  0.976190   5
5  0.952381   6
6  0.961905   7
7  0.961905   8
8  0.961905   9
9  0.961905  10

#### Human Resource Analytics

In [48]:
hr = pd.read_csv(r"C:\Users\dai\PycharmProjects\ML\Logistic_reg\HR_comma_sep.csv")
hr = pd.get_dummies(hr, drop_first=True)
X = hr.drop(["left"], axis=1)
y = hr.left

In [49]:
knn(X, y)

   accuracy   n
0  0.951100   1
1  0.946655   2
2  0.937542   3
3  0.941543   4
4  0.937319   5
5  0.942654   6
6  0.937986   7
7  0.942209   8
8  0.939542   9
9  0.941320  10

In [50]:
ss = StandardScaler()
def knn(X, y, ss):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25, stratify=y)
    X_trn_ss = ss.fit_transform(X_train)
    X_tst_ss = ss.transform(X_test)
    scores = []
    for n in range(1, 11):
        knn = KNeighborsClassifier(n_neighbors=n)
        knn.fit(X_trn_ss, y_train)
        y_pred = knn.predict(X_tst_ss)
        scores.append([accuracy_score(y_test, y_pred), n])

    scores = pd.DataFrame(scores, columns=["accuracy", "n"])
    scores.sort_values("accuracy", ascending=False)
    return scores

knn(X, y, ss)

   accuracy   n
0  0.966659   1
1  0.963325   2
2  0.950656   3
3  0.948433   4
4  0.940209   5
5  0.946210   6
6  0.942209   7
7  0.944210   8
8  0.940876   9
9  0.941543  10

In [51]:
ss = MinMaxScaler()
knn(X, y, ss)

   accuracy   n
0  0.966215   1
1  0.962658   2
2  0.951100   3
3  0.945543   4
4  0.939764   5
5  0.943321   6
6  0.940209   7
7  0.942432   8
8  0.938875   9
9  0.939987  10