In [144]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [145]:
arr1 = np.arange(400, 600, 20)
np.random.shuffle(arr1)
arr2 = np.linspace(0, 10, 10)
np.random.shuffle(arr2)
arr3 = np.linspace(0, 1, 10)
np.random.shuffle(arr3)

arr = np.array([arr1, arr2, arr3])
arr

array([[5.80000000e+02, 4.40000000e+02, 5.00000000e+02, 4.80000000e+02,
        5.20000000e+02, 4.20000000e+02, 5.40000000e+02, 4.00000000e+02,
        4.60000000e+02, 5.60000000e+02],
       [0.00000000e+00, 7.77777778e+00, 1.11111111e+00, 4.44444444e+00,
        1.00000000e+01, 8.88888889e+00, 3.33333333e+00, 2.22222222e+00,
        6.66666667e+00, 5.55555556e+00],
       [7.77777778e-01, 0.00000000e+00, 3.33333333e-01, 1.11111111e-01,
        6.66666667e-01, 4.44444444e-01, 1.00000000e+00, 5.55555556e-01,
        2.22222222e-01, 8.88888889e-01]])

In [146]:
df = pd.DataFrame(arr)
df = df.transpose().rename({0:"X1", 1:"X2", 2:"X3"}, axis=1)
df

      X1         X2        X3
0  580.0   0.000000  0.777778
1  440.0   7.777778  0.000000
2  500.0   1.111111  0.333333
3  480.0   4.444444  0.111111
4  520.0  10.000000  0.666667
5  420.0   8.888889  0.444444
6  540.0   3.333333  1.000000
7  400.0   2.222222  0.555556
8  460.0   6.666667  0.222222
9  560.0   5.555556  0.888889

In [147]:
ss = StandardScaler().set_output(transform="pandas")
ss.fit(df)
df1 = ss.transform(df)
df1

         X1        X2        X3
0  1.566699 -1.566699  0.870388
1 -0.870388  0.870388 -1.566699
2  0.174078 -1.218544 -0.522233
3 -0.174078 -0.174078 -1.218544
4  0.522233  1.566699  0.522233
5 -1.218544  1.218544 -0.174078
6  0.870388 -0.522233  1.566699
7 -1.566699 -0.870388  0.174078
8 -0.522233  0.522233 -0.870388
9  1.218544  0.174078  1.218544

In [148]:
df1.describe().loc[["mean", "std"],:]

                X1            X2            X3
mean -2.220446e-17  4.996004e-17 -4.440892e-17
std   1.054093e+00  1.054093e+00  1.054093e+00

In [149]:
mm = MinMaxScaler().set_output(transform="pandas")
mm.fit(df)
df2 = mm.transform(df)
df2

         X1        X2        X3
0  1.000000  0.000000  0.777778
1  0.222222  0.777778  0.000000
2  0.555556  0.111111  0.333333
3  0.444444  0.444444  0.111111
4  0.666667  1.000000  0.666667
5  0.111111  0.888889  0.444444
6  0.777778  0.333333  1.000000
7  0.000000  0.222222  0.555556
8  0.333333  0.666667  0.222222
9  0.888889  0.555556  0.888889

In [150]:
df2.describe().loc[["mean", "std"],:]

            X1        X2        X3
mean  0.500000  0.500000  0.500000
std   0.336406  0.336406  0.336406