In [1]:
from sklearn.linear_model import LinearRegression

from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [2]:
jobs = pd.read_csv(r"C:\Users\dai\Downloads\Datasets\Datasets\JobSalary2.csv")
jobs.set_index("S_No", inplace=True)
jobs

      Computer  Marketing  Engineer
S_No
1         84.0       55.0        75
2         90.0       53.0        70
3         63.0        NaN        88
4          NaN       50.0        77
5         63.0       41.0        89
6         75.0       54.0        85
7          NaN       51.0        96
8         77.0       64.0       105

In [3]:
imputer = SimpleImputer(strategy="mean").set_output(transform="pandas")
imputer.fit(jobs)
imputer.transform(jobs)

       Computer  Marketing  Engineer
S_No
1     84.000000  55.000000      75.0
2     90.000000  53.000000      70.0
3     63.000000  52.571429      88.0
4     75.333333  50.000000      77.0
5     63.000000  41.000000      89.0
6     75.000000  54.000000      85.0
7     75.333333  51.000000      96.0
8     77.000000  64.000000     105.0

In [4]:
concrete = pd.read_csv(r"Concrete_Data.csv")
X = concrete.drop("Strength", axis=1)
y = concrete["Strength"]

lr = LinearRegression()
lr.fit(X, y)
tst = pd.read_csv(r"testConcreteMissing.csv")

imputer = SimpleImputer(strategy="mean").set_output(transform="pandas")
imputer.fit(X)
tst = imputer.transform(tst)
print(tst.mean())
y_pred = lr.predict(tst)
print(y_pred)

Cement              310.309695
Blast                72.992559
Fly                  11.727739
Water               183.081040
Superplasticizer      3.386380
Coarse              851.922781
Fine                784.737282
Age                 149.690153
dtype: float64
[68.73718457 44.92754382 29.09844489 27.43221577 56.55844543 18.83513067
 50.30685651 81.86351485 24.60173472 42.79473839 43.44332935 66.11413244
 50.80518635 15.38709673]

In [5]:
from sklearn.model_selection import train_test_split

chem = pd.read_csv("ChemicalProcess.csv")
X = chem.drop("Yield", axis=1)
y = chem["Yield"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [6]:
imputer = SimpleImputer(strategy="mean").set_output(transform="pandas")
X_trn_imp = imputer.fit(X_train).transform(X_train)

X_tst_imp = imputer.transform(X_test)

In [7]:
lr = LinearRegression()
lr.fit(X_trn_imp, y_train)
y_pred = lr.predict(X_tst_imp)
mean_absolute_error(y_test, y_pred)

5.46562888453617

In [8]:
imputer = SimpleImputer(strategy="median").set_output(transform="pandas")
X_trn_imp = imputer.fit(X_train).transform(X_train)

X_tst_imp = imputer.transform(X_test)

In [9]:
lr = LinearRegression()
lr.fit(X_trn_imp, y_train)
y_pred = lr.predict(X_tst_imp)
mean_absolute_error(y_test, y_pred)

5.2164386091805754

#### Iterative Imputer

In [10]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [11]:
imputer = IterativeImputer(initial_strategy="mean")
X_trn_imp = imputer.fit_transform(X_train)
X_tst_imp = imputer.transform(X_test)
lr = LinearRegression()
lr.fit(X_trn_imp, y_train)
y_pred = lr.predict(X_tst_imp)
mean_absolute_error(y_test, y_pred)

6.451138259421783

In [12]:
air = pd.read_csv("Airquality.csv")

In [13]:
imputer = IterativeImputer(initial_strategy="mean").set_output(transform="pandas")
imp_air = imputer.fit_transform(air)
imp_air.isnull().sum()

Ozone      0
Solar.R    0
Wind       0
Temp       0
Month      0
Day        0
dtype: int64

In [14]:
imp_air

         Ozone     Solar.R  Wind  Temp  Month   Day
0    41.000000  190.000000   7.4  67.0    5.0   1.0
1    36.000000  118.000000   8.0  72.0    5.0   2.0
2    12.000000  149.000000  12.6  74.0    5.0   3.0
3    18.000000  313.000000  11.5  62.0    5.0   4.0
4   -12.272303  141.910042  14.3  56.0    5.0   5.0
..         ...         ...   ...   ...    ...   ...
148  30.000000  193.000000   6.9  70.0    9.0  26.0
149  29.203097  145.000000  13.2  77.0    9.0  27.0
150  14.000000  191.000000  14.3  75.0    9.0  28.0
151  18.000000  131.000000   8.0  76.0    9.0  29.0
152  20.000000  223.000000  11.5  68.0    9.0  30.0

[153 rows x 6 columns]