In [1]:
import pandas as pd

sent1='It is good practice for us.'
sent2='It was also good to know about it.'

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
tfidf=TfidfVectorizer()

In [4]:
new_text=tfidf.fit_transform([sent1,sent2])

In [5]:
new_text.toarray()

array([[0.        , 0.        , 0.44665616, 0.31779954, 0.44665616,
        0.31779954, 0.        , 0.44665616, 0.        , 0.44665616,
        0.        ],
       [0.36439074, 0.36439074, 0.        , 0.25926702, 0.        ,
        0.51853403, 0.36439074, 0.        , 0.36439074, 0.        ,
        0.36439074]])

In [6]:
import pandas as pd
df=pd.DataFrame(new_text.toarray(),columns=tfidf.get_feature_names_out())

In [7]:
df

,about,also,for,good,is,it,know,practice,to,us,was
0,0.000000,0.000000,0.446656,0.317800,0.446656,0.317800,0.000000,0.446656,0.000000,0.446656,0.000000
1,0.364391,0.364391,0.000000,0.259267,0.000000,0.518534,0.364391,0.000000,0.364391,0.000000,0.364391

In [8]:
tfidf=TfidfVectorizer(stop_words='english')

In [9]:
new_text=tfidf.fit_transform([sent1,sent2])

In [10]:
df=pd.DataFrame(new_text.toarray(),columns=tfidf.get_feature_names_out())

In [11]:
df

       good      know  practice
0  0.579739  0.000000  0.814802
1  0.579739  0.814802  0.000000

In [28]:
file=open('sample_sentences.txt','r')
text=(file.read().splitlines())
file.close

In [29]:
text

['Can you please pass me the salt?',
 'I will meet you at the park in 30 minutes.',
 'I need to finish this work before the deadline.',
 'What time does the movie start tonight?',
 'Please do not forget to lock the door when you leave.']

In [22]:
tfidf=TfidfVectorizer()

In [31]:
new_text=tfidf.fit_transform(text)
df=pd.DataFrame(new_text.toarray(),columns=tfidf.get_feature_names_out())

In [32]:
df

,30,at,before,can,deadline,do,does,door,finish,forget,...,the,this,time,to,tonight,what,when,will,work,you
0,0.000000,0.000000,0.000000,0.433291,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.206465,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.290180
1,0.360948,0.360948,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.171994,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.360948,0.000000,0.241731
2,0.000000,0.000000,0.381303,0.000000,0.381303,0.000000,0.000000,0.000000,0.381303,0.000000,...,0.181693,0.381303,0.000000,0.307633,0.000000,0.000000,0.000000,0.000000,0.381303,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.400736,0.000000,0.000000,0.000000,...,0.190953,0.000000,0.400736,0.000000,0.400736,0.400736,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.333753,0.000000,0.333753,0.000000,0.333753,...,0.159035,0.000000,0.000000,0.269269,0.000000,0.000000,0.333753,0.000000,0.000000,0.223518

In [37]:
file = open('sample_sentences.txt', 'r')
text = (file.read().splitlines())
tfidf = TfidfVectorizer(stop_words='english')
new_text = tfidf.fit_transform(text)
df = pd.DataFrame(new_text.toarray(), columns=tfidf.get_feature_names_out())

In [38]:
df

,30,deadline,does,door,finish,forget,leave,lock,meet,minutes,movie,need,park,pass,salt,start,time,tonight,work
0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.707107,0.707107,0.000000,0.000000,0.000000,0.0
1,0.5,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.5,0.5,0.000000,0.0,0.5,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
2,0.0,0.5,0.000000,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.000000,0.5,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.5
3,0.0,0.0,0.447214,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.447214,0.0,0.0,0.000000,0.000000,0.447214,0.447214,0.447214,0.0
4,0.0,0.0,0.000000,0.5,0.0,0.5,0.5,0.5,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0