In [1]:
import pandas as pd
import numpy as np
from numpy.random import logistic
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report, precision_score, recall_score, f1_score
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import warnings; warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, StandardScaler, MinMaxScaler

In [2]:
cancer = pd.read_csv(r"/Logistic_reg/BreastCancer.csv")
X = cancer.drop(["Code", "Class"], axis=1)
y = cancer["Class"]

In [3]:
def knn(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25, stratify=y)
    scores = []
    for n in range(1, 11):
        knn = KNeighborsClassifier(n_neighbors=n)
        knn.fit(X_train, y_train)
        y_pred = knn.predict(X_test)
        scores.append([accuracy_score(y_test, y_pred), n])

    scores = pd.DataFrame(scores, columns=["accuracy", "n"])
    scores.sort_values("accuracy", ascending=False)
    return scores
knn(X, y)

   accuracy   n
0  0.957143   1
1  0.933333   2
2  0.971429   3
3  0.961905   4
4  0.976190   5
5  0.952381   6
6  0.961905   7
7  0.961905   8
8  0.961905   9
9  0.961905  10

#### Human Resource Analytics

In [4]:
hr = pd.read_csv(r"/Logistic_reg/HR_comma_sep.csv")
hr = pd.get_dummies(hr, drop_first=True)
X = hr.drop(["left"], axis=1)
y = hr.left

In [5]:
knn(X, y)

   accuracy   n
0  0.951100   1
1  0.946655   2
2  0.937542   3
3  0.941543   4
4  0.937319   5
5  0.942654   6
6  0.937986   7
7  0.942209   8
8  0.939542   9
9  0.941320  10

In [6]:
ss = StandardScaler()
def knn(X, y, ss):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25, stratify=y)
    X_trn_ss = ss.fit_transform(X_train)
    X_tst_ss = ss.transform(X_test)
    scores = []
    for n in range(1, 11):
        knn = KNeighborsClassifier(n_neighbors=n)
        knn.fit(X_trn_ss, y_train)
        y_pred = knn.predict(X_tst_ss)
        scores.append([accuracy_score(y_test, y_pred), n])

    scores = pd.DataFrame(scores, columns=["accuracy", "n"])
    scores.sort_values("accuracy", ascending=False)
    return scores

knn(X, y, ss)

   accuracy   n
0  0.966659   1
1  0.963325   2
2  0.950656   3
3  0.948433   4
4  0.940209   5
5  0.946210   6
6  0.942209   7
7  0.944210   8
8  0.940876   9
9  0.941543  10

In [7]:
ss = MinMaxScaler()
knn(X, y, ss)

   accuracy   n
0  0.966215   1
1  0.962658   2
2  0.951100   3
3  0.945543   4
4  0.939764   5
5  0.943321   6
6  0.940209   7
7  0.942432   8
8  0.938875   9
9  0.939987  10

In [8]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,MinMaxScaler
df=pd.read_csv('Glass.csv')
df=pd.DataFrame(df)
mm=MinMaxScaler()
ss=StandardScaler()
def knnss(X, y, ss):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25, stratify=y)
    X_trn_ss = ss.fit_transform(X_train)
    X_tst_ss = ss.transform(X_test)
    scores = []
    for n in range(1, 11):
        knn = KNeighborsClassifier(n_neighbors=n)
        knn.fit(X_trn_ss, y_train)
        y_pred = knn.predict(X_tst_ss)
        scores.append([accuracy_score(y_test, y_pred), n])

    scores = pd.DataFrame(scores, columns=["accuracy", "n"])
    scores.sort_values("accuracy", ascending=False)
    return scores

X = df.drop(['Type'], axis=1)
y = df['Type']
print(knnss(X, y, ss))

def knnmm(X, y, mm):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25, stratify=y)
    X_trn_ss = mm.fit_transform(X_train)
    X_tst_ss = mm.transform(X_test)
    scores = []
    for n in range(1, 11):
        knn = KNeighborsClassifier(n_neighbors=n)
        knn.fit(X_trn_ss, y_train)
        y_pred = knn.predict(X_tst_ss)
        scores.append([accuracy_score(y_test, y_pred), n])

    scores = pd.DataFrame(scores, columns=["accuracy", "n"])
    scores.sort_values("accuracy", ascending=False)
    return scores

print(knnmm(X, y, mm))

def knn(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25, stratify=y)
    scores = []
    for n in range(1, 11):
        knn = KNeighborsClassifier(n_neighbors=n)
        knn.fit(X_train, y_train)
        y_pred = knn.predict(X_test)
        scores.append([accuracy_score(y_test, y_pred), n])

    scores = pd.DataFrame(scores, columns=["accuracy", "n"])
    scores.sort_values("accuracy", ascending=False)
    return scores

print(knn(X, y))

   accuracy   n
0  0.800000   1
1  0.815385   2
2  0.753846   3
3  0.738462   4
4  0.676923   5
5  0.692308   6
6  0.692308   7
7  0.661538   8
8  0.661538   9
9  0.646154  10
   accuracy   n
0  0.753846   1
1  0.723077   2
2  0.676923   3
3  0.769231   4
4  0.692308   5
5  0.707692   6
6  0.646154   7
7  0.646154   8
8  0.630769   9
9  0.600000  10
   accuracy   n
0  0.753846   1
1  0.753846   2
2  0.723077   3
3  0.723077   4
4  0.723077   5
5  0.723077   6
6  0.692308   7
7  0.707692   8
8  0.692308   9
9  0.676923  10

## Vehicle Silhouttes

In [9]:
df=pd.read_csv('Vehicle.csv')
df=pd.DataFrame(df)
x=df.drop(["Class"], axis=1)
y=df['Class']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=25, stratify=y)
scores = []
for n in range(1, 11):
    knn = KNeighborsClassifier(n_neighbors=n)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    scores.append([accuracy_score(y_test, y_pred), n])
scores = pd.DataFrame(scores, columns=["accuracy", "n"])
scores.sort_values("accuracy", ascending=False)
print(precision_score(y_test, y_pred,average="weighted"))
print(recall_score(y_test, y_pred,average="weighted"))
#print(recall_score(y_test, y_pred))
#print(f1_score(y_test, y_pred))
print(scores)
print(classification_report(y_test, y_pred))

ss=StandardScaler()
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=25, stratify=y)
X_trn_ss = ss.fit_transform(X_train)
X_tst_ss = ss.transform(X_test)
scores = []
for n in range(1, 11):
    knn = KNeighborsClassifier(n_neighbors=n)
    knn.fit(X_trn_ss, y_train)
    y_pred = knn.predict(X_tst_ss)
    scores.append([accuracy_score(y_test, y_pred), n])

scores = pd.DataFrame(scores, columns=["accuracy", "n"])
scores.sort_values("accuracy", ascending=False)
print(precision_score(y_test, y_pred,average="weighted"))
print(recall_score(y_test, y_pred,average="weighted"))
#print(recall_score(y_test, y_pred))
#print(f1_score(y_test, y_pred))
print(scores)
print(classification_report(y_test, y_pred))

0.6215124936938289
0.6377952755905512
   accuracy   n
0  0.641732   1
1  0.622047   2
2  0.653543   3
3  0.649606   4
4  0.641732   5
5  0.637795   6
6  0.653543   7
7  0.641732   8
8  0.629921   9
9  0.637795  10
              precision    recall  f1-score   support

         bus       0.72      0.75      0.74        65
        opel       0.49      0.39      0.43        64
        saab       0.48      0.48      0.48        65
         van       0.80      0.95      0.87        60

    accuracy                           0.64       254
   macro avg       0.62      0.64      0.63       254
weighted avg       0.62      0.64      0.63       254

0.6924561741604048
0.7086614173228346
   accuracy   n
0  0.653543   1
1  0.645669   2
2  0.728346   3
3  0.716535   4
4  0.696850   5
5  0.692913   6
6  0.700787   7
7  0.696850   8
8  0.688976   9
9  0.708661  10
              precision    recall  f1-score   support

         bus       0.86      0.94      0.90        65
        opel       0.56      0.53      0.54        64
        saab       0.58      0.45      0.50        65
         van       0.78      0.93      0.85        60

    accuracy                           0.71       254
   macro avg       0.69      0.71      0.70       254
weighted avg       0.69      0.71      0.70       254